baseURL = "http://example.org/"
languageCode = "en-gb"
title = "Aleix Murtra"
theme = "hermit"

[params]
  homeSubtitle = "SRE / Systems Engineer @ mango.com"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/aleixmurtra"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/aleix-murtra/"

  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/alemuro"

  [[params.social]]
    name = "github"
    url = "https://github.com/alemuro"