baseURL = "https://aleix.cloud"
languageCode = "en-gb"
theme = "hermit"
title = "Aleix Murtra"
enableGitInfo = true
pygmentsCodefences  = true
pygmentsUseClasses  = true
enableEmoji = true
rssLimit = 10

[author]
    name = "Aleix Murtra"

[menu]

    [[menu.main]]
    name = "Projects"
    url = "projects/"
    weight = 20

    [[menu.main]]
    name = "About me"
    url = "about-me/"
    weight = 20

[params]
    themeColor = "#ffffff"
    #bgImg = "https://res.cloudinary.com/dtikuanda/image/upload/c_scale,q_auto,w_1920/v1563702307/4k-wallpaper-clouds-dawn-1261728_geguhc.jpg"

    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04 -0700"

    footerCopyright = " &#183; aleix.cloud &#183; <a href='https://www.pexels.com/photo/scenic-view-of-mountains-during-dawn-1261728/' target='_blank'>Background photo</a>"
    homeSubtitle = "DevOps Engineer @ Wallbox"

    justifyContent = true

    customCSS = [ "css/personalized.css" ]

    [[params.social]]
    name = "twitter"
    url = "https://twitter.com/aleixmurtra"
    [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/aleix-murtra/"
    [[params.social]]
    name = "instagram"
    url = "https://instagram.com/aleixmurtra"
    [[params.social]]
    name = "github"
    url = "https://github.com/alemuro"
