[[redirects]]
force = false
from = "/blog"
status = 301
to = "https://dev.to/alemuro"
[[redirects]]
force = false
from = "/github"
status = 301
to = "https://github.com/alemuro"
[[redirects]]
force = false
from = "/n26"
status = 302
to = "https://n26.com/r/aleixm9758"
[[redirects]]
force = false
from = "/booking"
status = 302
to = "https://www.booking.com/?aid=1385028"
